Adds the ability to se the number of loops for an animation
ImageOptim/gifski pull request #151
Opened 2020-11-26 04:29 UTC by 0bmay

The changes below allow an animation to be looped X number of times instead of no looping or looping forever.

2020-11-26 22:04 UTC, kornelski commented
Thanks for the PR.

Having separate `once` and `loop_count` fields is un-idiomatic for Rust. Could you change it to something like this? https://docs.rs/gif/0.11.1/gif/enum.Repeat.html

The C struct could have `repeat: 0` meaning infinite. Unfortunately the struct is exposed, so any change is an API break anyway.

2020-11-26 22:38 UTC, 0bmay commented
might be best to remove the once and use loop_count or repeat that can hold a value of -1 and above, as 0 would be a valid repeat count (or don't repeat/loop) This would match the gifsicle looping values.

Thoughts?

2020-11-26 23:36 UTC, 0bmay commented
While thinking on my run, you are correct.. 0 is repeat forever and -1 is no repeats for gifsicle...  but the above question still can work, remove once, rename loop_count to repeat and have values of -1 and 0+... with 0 repeating forever.

2020-11-26 23:41 UTC, kornelski commented
Yeah, the C struct could follow gifsicle, and the Rust struct should follow Rust's gif crate. It may even re-export: `pub use gif::Repeat`.

2020-11-27 00:00 UTC, 0bmay commented
OK.. sounds good..  I will have to figure out how to use Rust's gif crate..  This project is my first time working with Rust.

2020-11-27 00:26 UTC, kornelski commented
The gif crate is already available under global `gif` name.

To "copy" their repeat type add in `lib.rs`


```rust
pub use gif::Repeat;
```

and then `crate::Repeat` path will refer to it. You can use that type in the settings struct.

2020-11-27 22:38 UTC, 0bmay commented
Attempting to add in gif::Repeat into the struct and I get the following error while compiling:

```
 pub repeat: gif::Repeat,
 this field does not implement `Copy`
```

defined as:
```
    pub fast: bool,
    /// Sets the looping method for the image sequence.
    pub repeat: gif::Repeat,
}
```

I don't know enough about Rust to know if this is an easy fix or if I should just mimic the gifsicle method.

2020-11-28 01:28 UTC, sindresorhus requested changes

2020-11-28 01:28 UTC, sindresorhus commented on src/bin/gifski.rs
> +                            .help("Number of loops the animation is shown")
```suggestion
                            .help("Number of times the animation is repeated")
```

The previous sentence doesn't read very well.

2020-11-28 01:28 UTC, sindresorhus commented on src/c_api.rs
> +    /// the loop count if once is false. 0 is forever.
```suggestion
    /// The loop count if `once` is false. 0 to loop forever.
```

2020-11-28 01:28 UTC, sindresorhus commented on src/encoderust.rs
> +                    }
```suggestion
                    let repetitions = settings.loop_count > 0 ? gif::Repeat::Finite(settings.loop_count) : gif::Repeat::Infinite;
                    enc.write_extension(gif::ExtensionData::Repetitions(repetitions))?;
```

Not sure if this is valid Rust code, but reads a bit clearer to me.

2020-11-28 01:28 UTC, sindresorhus commented on src/c_api.rs
>      pub once: bool,
`Resize to max this width if non-0` => `Resize to max this width if non-0.` since you did that change in the other place already.

2020-11-28 01:28 UTC, sindresorhus commented on src/lib.rs
> +    /// The loop count if once is false. 0 is forever.
```suggestion
    /// The loop count if `once` is false. 0 to loop forever.
```

2020-11-28 01:29 UTC, sindresorhus commented
> Attempting to add in gif::Repeat into the struct and I get the following error while compiling:

Just a tip: When asking questions about changes, push your changes, even if broken, so the reviewer can see the context.

2020-11-28 01:32 UTC, sindresorhus commented
@0bmay I have no experience with Rust, but from quickly Googling the error, it's clear that it's because `GifskiSettings` derives the `Copy` trait, but `gif::Repeat` does not. So you need to find a way to make it copyable.

2020-11-28 02:58 UTC, 0bmay commented
> @0bmay I have no experience with Rust, but from quickly Googling the error, it's clear that it's because `GifskiSettings` derives the `Copy` trait, but `gif::Repeat` does not. So you need to find a way to make it copyable.

Yes, I found that before posting the question here.  The [rust docs](https://doc.rust-lang.org/stable/std/marker/trait.Copy.html#when-should-my-type-be-copy) states that if

> Generally speaking, if your type can implement Copy, it should.

That means making a request to the gif crate to make the gif::Repeat enum copyable. Unless there's a different method that I should do.  Again, total Rust noob here..

2020-12-16 04:33 UTC, sindresorhus commented
@kornelski Any thoughts on this?

2020-12-16 10:12 UTC, kornelski commented
Indeed: https://github.com/image-rs/image-gif/pull/92

Until gif crate makes it `Copy`, you need to define your own `enum Repeat` that is copyable, and convert to gif crate's repeat accordingly.

2020-12-17 17:32 UTC, 0bmay commented
I have made the changes to use a similar Repeat enum and use that throughout the code.  The output is what would be expected with the following command line arguments:
--quality 90 <no --repeat used> : repeats forever
--quality 90 --repeat 0     : repeats forever
--quality 90 --repeat -1    : no repeat
--quality 90 --repeat 1     : repeats once
--quality 90 --repeat 3     : repeats thrice
--quality 100 <no --repeat used> : repeats forever
--quality 100 --repeat 0     : repeats forever
--quality 100 --repeat -1    : no repeat
--quality 100 --repeat 1     : repeats once
--quality 100 --repeat 3     : repeats thrice
<no --quality used> <no --repeat used> : repeats forever

If this looks good and passes, I will update the macOS app with similar updates.

2020-12-17 17:53 UTC, merged

2020-12-17 17:53 UTC, kornelski commented
Looks good, thank you!

2020-12-17 17:56 UTC, 0bmay commented
Awesome. Thank you.